#! /bin/sh
bspc config focus_follows_pointer 				true 
bspc config pointer_follows_focus 				true
bspc config border_width                        2
bspc config focused_border_color                '#696B6A'
bspc config window_gap                          2

 
bspc config split_ratio                         0.5
bspc config borderless_monocle                  true
bspc config gapless_monocle                     true
bspc config focus_by_distance                   true
 
bspc monitor LVDS -d 1 2 3 4 5
bspc monitor DFP1 -d 6 7 8 9 10 
bspc config -d 1 top_padding 17
bspc config -d 2 top_padding 17
bspc config -d 3 top_padding 17
bspc config -d 4 top_padding 17
bspc config -d 5 top_padding 17
bspc config -d 6 top_padding 5
bspc config -d 7 top_padding 5
bspc config -d 8 top_padding 5
bspc config -d 9 top_padding 5
bspc config -d 10 top_padding 5
bspc config bottom_padding 5
bspc config left_padding   5
bspc config right_padding  5
bspc rule -a scratchpad floating=on 
